### ISSUE TITLE
"No module named tvdb_api" after installing Python with Homebrew and tvdb_api with pip

### ISSUE THREAD

**Issue by craiga** [chipotle/tvdb_itunes#1]
After selecting a show an episode in iTunes then activating "Get TV Show Data" from the Script menu, I get the following error in a dialog:

> Traceback (most recent call last):
>   File "<string>", line 4, in <module>
> ImportError: No module named tvdb_api

It started working once I ran `sudo easy_install tvdb_api`, as advised, from the command line. However, the `readme` seemed to suggest that the `pip` method was somehow preferable.

**Comment by chipotle** [comment]
Hmm. I'm pretty sure _I_ used pip, but I'll remove that line from the readme if it turns out it's bad advice!

**Comment by chipotle** [comment]
I wonder if the issue is the Homebrew-installed Python -- is it possible pip installed tvdb_api for you in OS X's system Python for some reason?

**Comment by craiga** [comment]
I think the problem is that `pip` is installing for the `brew`-installed Python, but OS X's Python is still hanging about.

```
$ which python
/usr/bin/python
$ which pip
/usr/local/bin/pip
```
